### ISSUE TITLE
Support for sequelize v4

### ISSUE THREAD

**Issue by cbargren** [rochejul/sequelize-mocking#13]
The library doesn't appear to be working properly with the latest version of sequelize. Installing v4.1.1 and running the tests results in the following failures: https://gist.github.com/cbargren/1191a5f64a9aa7682800c1f185c18c8b.

Sequelize v4 breaking changes: http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by rochejul** [comment]
Hi @cbargren 

Indeed, this tools was not design for the new sequelize major version

I will try for the next weeks to make some evolutions

Regards

**Comment by cbargren** [comment]
Awesome, thanks!
