### ISSUE TITLE
timestamps being returned as string

### ISSUE THREAD

**Issue by abeMedia** [rochejul/sequelize-mocking#15]
I have a timestamp field in my table which I'm trying to mock, however it seems to simply get returned as a string when using sequelize-mocking. It might be an idea to expose `transformFixtureDataFn` from sequelize-fixtures to do something like the following:

```js
sequelize_fixtures.loadFile('fixtures/users.json', models, {
  transformFixtureDataFn: function (data) {
    if(data.createdAt) {
      data.createdAt = new Date(data.createdAt);
    }
    return data;
  }
})
```

**Comment by rochejul** [comment]
Hi @abeMedia

Sure, it seems this is a part of the sequelize fixtures functionalities

I try to give an enhancement for the next release

Regards
