### ISSUE TITLE
Unable to mock sequelize transactions

### ISSUE THREAD

**Issue by ricardobotto** [rochejul/sequelize-mocking#24]
Hi,

I'm unable to mock tests that uses sequelize transactions.

Mocks currently generating **START TRANSACTION** queries which corresponds to the MySQL syntax.

I already tested using SQLITE as project default database and it correctly generates a query: 
**BEGIN DEFERRED TRANSACTION**

Using following transaction templates:
`	sql.transaction().then(function (t) {
		return t.commit();
	});
`

`
	sql.transaction(function (t) {
	});
`

Both return the following errors:
> Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: near "START": syntax error
>     at Query.formatError (./node_modules/sequelize/lib/dialects/sqlite/query.js:424:16)
>     at afterExecute (./node_modules/sequelize/lib/dialects/sqlite/query.js:120:32)
>     at replacement (./node_modules/sqlite3/lib/trace.js:19:31)
>     at Statement.errBack (./node_modules/sqlite3/lib/sqlite3.js:16:21)

Am I doing somthing wrong regarding mocks configuration? Here is my Database Instance
`const sql = new Sequelize(config.db.database, config.db.username, config.db.password, {
	host: config.db.host,
	dialect: config.db.driver,
	logging: false,
	operatorsAliases: Sequelize.Op
});`

**Comment by rochejul** [comment]
Hi @ricardobotto 

Could you provide an attachment with a concrete example of your issue please ?

Many thanks

Regards

**Comment by ricardobotto** [comment]
Hi @rochejul

I'm attaching a more complete example, hope it helps. Transactions structures can be found in controller.txt.

[controller.txt](https://github.com/rochejul/sequelize-mocking/files/1622505/controller.txt)
[index.txt](https://github.com/rochejul/sequelize-mocking/files/1622506/index.txt)
[test-spec.txt](https://github.com/rochejul/sequelize-mocking/files/1622507/test-spec.txt)
[userModel.txt](https://github.com/rochejul/sequelize-mocking/files/1622508/userModel.txt)

Thanks for helping :)

**Comment by rochejul** [comment]
Many thanks !

I try to take some times on the next days to look on it

Thanks

**Comment by djfabrix** [comment]
I have the same problem.
Any news about resolution?
Thanks in advance

**Comment by rochejul** [comment]
Analysis in progress. It seems we could have not the expecter QueryGenerator instance, and we use the "abstract" one instead the sqlite dedicated.

Look to find a fix

Regards

**Comment by rochejul** [comment]
Ok, it seems the "queryInterface" property is not updated (new creation since Sequelize 4.X ?) --> https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L243

so like the dialect, we have to override it.

**Comment by rochejul** [comment]
Will be deployed soon

**Comment by ekrotenko** [comment]
Any updates? Still tests fail on calls of transaction.commit()/transaction.rollback()

**Comment by rochejul** [comment]
Hi @ekrotenko 
Could you please them to give a full example please ?  A tiny project to illustrate the issue

Regards
