### ISSUE TITLE
Can't use useHandler or return null. 

### ISSUE THREAD

**Issue by aconfee** [rochejul/sequelize-mocking#28]
Hello! I currently have the following, mostly default example, code which produces the error 'TypeError: MockDummyDao.$useHandler is not a function.'

```
import SequelizeMock from 'sequelize-mock';
const dbMock = new SequelizeMock();

const MockDummyDao = dbMock.define('dummy'); 

MockDummyDao.$useHandler((query) => {
  if(query === 'findById') {
    return null;
  };
});
```

Ultimately, all I'm trying to do is return a `null`, just null, not an object. This is what Sequelize actually returns when a record can't be found. This will then consistently test the following code in my service:

```
const dummyRow: any = await this.dummyDao.findById(2)
  .catch((e) => { console.error(e); });

 if(_.isNull(dummyRow) || _.isUndefined(dummyRow)){
    return null;
  }

return new Dummy(dummyRow.get('message'));
```
Which behaves as expected live.

Any best way to return null, or insight into why $useHandler doesn't exist would be a huge help! Thanks!

**Comment by rochejul** [comment]
Hi

What is the content of your "sequelize-mock"? Could you provide a tiny example to illustrate it please?

Moreover, if I read well: we could see this:

````
Note: This is not an equivalent mock of Sequelize's built in QueryInterface at the moment. The built in object for Sequelize is undocumented and is marked as @private in their code, meaning it is not likely something to be relied on. If this changes it can be mocked here. Functions have been prefixed with the mock prefix ($) for this reason.
````

That means these methods are **considerated as private** and should not be called direclty.

Anyway, I could have a look to understand what after the mocking, these methods are not exposed

Many thanks

Regards

**Comment by rochejul** [comment]
See https://sequelize-mock.readthedocs.io/en/stable/api/queryinterface/

**Comment by rochejul** [comment]
Close issue, due to no more feedbacks
