### ISSUE TITLE
Original Sequelize options not passed to mock instance.

### ISSUE THREAD

**Issue by marcuslieberenzdev** [rochejul/sequelize-mocking#32]
Hi,

I think the second parameter here should be `options` instead of `fixtureFilePath`. Otherwise the original sequelize config options (e.g. `logging: false`) are not passed through to the mock instance.

https://github.com/rochejul/sequelize-mocking/blob/7204464c6ba0cbc6d8fdc7e27db6917ea91a1e91/lib/sequelize-mocking-mocha.js#L33

Regards
Marcus

**Comment by rochejul** [comment]
I use a partialRight function to provide the options parameter
See https://github.com/rochejul/sequelize-mocking/blob/7204464c6ba0cbc6d8fdc7e27db6917ea91a1e91/lib/sequelize-mocking-mocha.js#L31

**Comment by marcuslieberenzdev** [comment]
Hi,

understood. However, I don't provide a `fixtureFilePath` and when I debug, the `options` are not passed to `SequelizeMocking.create`. This happens because the parameter `fixtureFilePath` is passed to

https://github.com/rochejul/sequelize-mocking/blob/7204464c6ba0cbc6d8fdc7e27db6917ea91a1e91/lib/sequelize-mocking-mocha.js#L33

which is `null` in this case and thus overwriting the `options` param provided through `_.partialRight`.

**Comment by rochejul** [comment]
Hi @marcuslieberenzdev 

Could you provide your test file? I will use it for debugging.

Many thanks

**Comment by rochejul** [comment]
Close due to inactivity
