### ISSUE TITLE
Vulnerability of Prototype Pollution in loadash.

### ISSUE THREAD

**Issue by MuuKojima** [rochejul/sequelize-mocking#33]
Hi,
I use this library and really like it!
But it seems to be a vulnerability like this.

![スクリーンショット 2019-08-11 18 58 52](https://user-images.githubusercontent.com/3895795/62832908-cb9e0280-bc70-11e9-988e-3b622d6d7803.png)

Could you fix it?

Regards.

**Comment by rochejul** [comment]
Hi @MuuKojima 

Sure, I try to release a 2.0.1 as soon as possible

Many thanks

**Comment by MuuKojima** [comment]
@rochejul 
Thank you so much!
