### ISSUE TITLE
Getting error on aftereach restore

### ISSUE THREAD

**Issue by justechn** [rochejul/sequelize-mocking#4]
I am getting the following error from this library when the tests are done
`ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails`

This is obviously because I have foreign keys in my database, so I looked to see how sequelize handles this internally and I found in the query-interface.js on line 238

```
return self.sequelize.query('PRAGMA foreign_keys = OFF', options).then(function() {
    return dropAllTables(tableNames).then(function() {
        return self.sequelize.query('PRAGMA foreign_keys = ON', options);
```

So I tried to modify the restore function in your module to do the same

```
return mockedSequelize
    .query('PRAGMA foreign_keys = OFF', {raw: true})
    .then(function () {
        return mockedSequelize
            .drop({ 'logging': logging })
            .then(function () {
                logging && console.log('SequelizeMocking - Context is restored');
            });
    });
```

but I still get the same error, so something is not working. Do you have any idea what I am doing wrong?

**Comment by justechn** [comment]
I think I found a solution. The native sequelize dropAllTables works great.

```
return mockedSequelize
            .getQueryInterface()
            .dropAllTables({ 'logging': logging })
            .then(function () {
                logging && console.log('SequelizeMocking - Context is restored');
            });
```

should I submit a PR to get this changed?

**Comment by rochejul** [comment]
Sure, this is a good idea

Maybe try to add some tests to check your needs into the pull request

Many thanks for your work

Cheers

**Comment by anibali** [comment]
Further to this (and perhaps scarier), I find that the existing version of `restore` drops all of the tables in my actual database. The `dropAllTables` solution does not have this issue.

**Comment by rochejul** [comment]
Hi,

Have you got a pull-request ?

Shall I only change this line https://github.com/rochejul/sequelize-mocking/blob/master/lib/sequelize-mocking.js#L226 with:

````javascript
return mockedSequelize
    .getQueryInterface()
    .dropAllTables({ 'logging': logging })
    .then(function () {
        logging && console.log('SequelizeMocking - Context is restored');
   });
````

Many thanks for your feedback

Cheers

**Comment by justechn** [comment]
Yes, that is the change I made. 
https://github.com/justechn/sequelize-mocking/commit/73f9e9b65312ac1b529235ba971de09a9aa0dc2c

I forked the repo and made the changes, but it caused the tests to fail. I have not had time to dig into why.

**Comment by rochejul** [comment]
Copy that

If  I have some times, I will look on it

Many thanks

Cheers
